Sending back the error message of Facebook as an error for some funct…
paked/messenger pull request #14
Opened 2016-10-04 12:13 UTC by Depado

…ion calls

Also quick typo in the comments of the `Read` struct. 
I didn't include much detail in the error message (the code is already in the message anyway), and I have no idea what the `FbtraceID` is about ^^

Cheers

2016-10-06 00:28 UTC, paked requested changes
Sorry it took me a while to get back to this.

This is heading in the right direction, I've left a few comments regarding minor stuff like documentation etc.

After you've fixed those errors, It'd be great if you could take a stab at handling these errors in other places. I imagine that they show up in other places too, like:
- https://github.com/paked/messenger/blob/master/messenger.go#L125
- https://github.com/paked/messenger/blob/master/response.go#L139
- https://github.com/paked/messenger/blob/master/response.go#L175
- https://github.com/paked/messenger/blob/master/response.go#L203

... And probably more.

Let me know if you're up to it, if not we can just work on getting these merged.

2016-10-06 00:28 UTC, paked commented on response.go
> +	FbtraceID string `json:"fbtrace_id"`
Let's rename this field to `FBTraceID`

2016-10-06 00:28 UTC, paked commented on response.go
> +// QueryResponse is the response sent back by facebook when setting up things
Capitalise Facebook

2016-10-06 00:28 UTC, paked commented on response.go
> +// QueryError is representing an error sent back by facebook
Capitalise Facebook

2016-10-06 00:31 UTC, paked commented
Also, on another note: The commit you've sent doesn't seem to have an author associated with it. [I'd follow the instructions here](https://help.github.com/articles/set-up-git/#setting-up-git). Once you've done that, `git commit --amend && git push -f` should fix everything up!

2016-10-06 08:43 UTC, Depado commented
Hello there ! Thanks for the feedback, I'll have a look at this today.

2016-10-06 09:02 UTC, Depado commented
Hey there. 
So I made the changes you requested (comments and field name) and also added this behavior for the other functions that can potentially fail. 

Also I fixed my author thing I think. 

Does it look good to you ?

2016-10-06 09:46 UTC, paked requested changes
This looks great. Before I merge it in, I'd like to reduce the amount of code repetition from this new Facebook error handling code.

Do you think you could move it into something like`func checkFacebookError(r io.Reader) err`?

After this is done we'll be able to merge this straight in.

2016-10-06 13:04 UTC, Depado commented
Sure thing :)

2016-10-06 13:19 UTC, Depado commented on messenger.go
> -	err = json.NewDecoder(resp.Body).Decode(&p)
That would break everything :smile:

2016-10-06 13:24 UTC, Depado commented
There's an issue with the `ProfileByID` function as the returned JSON is either the profile of the user or an error. (So it can either be a `Profile` or a `QueryResponse` type) I'll give that a try later. Thanks for the feedback :)

2016-10-07 03:33 UTC, paked commented on messenger.go
> -	err = json.NewDecoder(resp.Body).Decode(&p)
😆

2016-10-07 03:38 UTC, paked commented
Alright. Good luck!

2016-10-07 10:26 UTC, Depado commented
Hey there. Found a way to handle that kind of corner case. Could you review the changes ? 
It works pretty fine from what I can see (for example try to `ProfileByID(0)` it will return an error).

2016-10-07 13:28 UTC, merged

2016-10-07 13:33 UTC, paked commented
![https://media.giphy.com/media/6fxTfCp307Hnq/giphy.gif](https://media.giphy.com/media/6fxTfCp307Hnq/giphy.gif)


@Depado Thanks for your persistence on this PR! I'm very grateful 🎈