Support sent attachment by url.
paked/messenger pull request #15
Opened 2016-10-08 04:32 UTC by appleboy

Example:

```go
client.Attachment(To, "image", "https://example.com/xxx.png")
client.Attachment(To, "audio", "https://example.com/xxx.mp3")
client.Attachment(To, "video", "https://example.com/xxx.mp4")
client.Attachment(To, "file", "https://example.com/xxx.pdf")
```

Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

2016-10-08 05:06 UTC, paked requested changes
Thanks for this PR! We really need to work on keeping up with Facebook's API changes. I've left a few comments, but everything looks ready to go after they're fixed!

2016-10-08 05:06 UTC, paked commented on messenger.go
> +// Attachment send image, audio, video and file attachment.
Let's just clear up the grammar here a bit... Maybe something like the following:

> Attachment sends an image, sound, video or a regular file to a given recipient.

2016-10-08 05:06 UTC, paked commented on messenger.go
> +func (m *Messenger) Attachment(to Recipient, dataType, url string) error {
When the constant attachment type below is implemented, this signature will need to change too.

2016-10-08 05:06 UTC, paked commented on response.go
> +func (r *Response) Attachment(dataType, url string) error {
We should probably get rid of the magic values introduce by the `dataType` string.

Something like the following would be great:

```go
type AttachmentType string

const (
   ImageAttachment AttachmentType = "image"
   AudioAttachment AttachmentType = "audio"
   VideoAttachment AttachmentType = "video"
   FileAttachment AttachmentType = "file"
)
```

So we can then change this function's signature to `func(to Recipient, dataType AttachmentType, url string) error`

2016-10-08 05:06 UTC, paked commented on response.go
> +// Attachment send image, audio, video and file attachment
Maybe something like:

> Attachment sends an image, sound, video or a regular file to a chat.

2016-10-08 06:09 UTC, appleboy commented on response.go
> +func (r *Response) Attachment(dataType, url string) error {
I don't know why need defined const value for `AttachmentType`? We can make some example to explain how to use `Attachment` method in the second argument.

2016-10-08 06:10 UTC, appleboy commented on response.go
> +// Attachment send image, audio, video and file attachment
Done!

2016-10-08 06:10 UTC, appleboy commented on messenger.go
> +// Attachment send image, audio, video and file attachment.
Done!

2016-10-08 06:16 UTC, appleboy commented on response.go
> +func (r *Response) Attachment(dataType, url string) error {
We need `AttachmentType` const value unless implement the following method.

```go
func (m *Messenger) ImageAttachment
func (m *Messenger) AudioAttachment
func (m *Messenger) VideoAttachment
func (m *Messenger) FileAttachment
```
and 

```diff
m := SendStructuredMessage{
    Recipient: r.to,
    Message: StructuredMessageData{
        Attachment: StructuredMessageAttachment{
-           Type: dataType,
+           Type: FileAttachment,
            Payload: StructuredMessagePayload{
                Url: url,
            },
        },
    },
}
```

2016-10-09 02:06 UTC, paked commented on response.go
> +func (r *Response) Attachment(dataType, url string) error {
I prefer the constant method, it's less repetition.

2016-10-09 02:26 UTC, appleboy commented on response.go
> +func (r *Response) Attachment(dataType, url string) error {
@paked Done. Please review again.

2016-10-09 02:27 UTC, appleboy commented
@paked Already Done.

2016-10-09 02:27 UTC, appleboy commented on messenger.go
> +func (m *Messenger) Attachment(to Recipient, dataType, url string) error {
Done!

2016-10-09 02:30 UTC, appleboy commented
We can change the example:

```go
client.Attachment(To, messenger.ImageAttachment, "https://cdn3.iconfinder.com/data/icons/picons-social/57/16-apple-256.png")
client.Attachment(To, messenger.AudioAttachment, "https://archive.org/download/testmp3testfile/mpthreetest.mp3")
client.Attachment(To, messenger.VideoAttachment, "http://www.sample-videos.com/video/mp4/480/big_buck_bunny_480p_5mb.mp4")
client.Attachment(To, messenger.FileAttachment, "http://open.qiniudn.com/where-can-you-use-golang.pdf")
```

2016-10-09 03:28 UTC, merged

2016-10-09 03:29 UTC, paked commented
Thanks for the PR yet again @appleboy. It's great to see your continuing support for this project 💯 

![https://media.giphy.com/media/MSS0COPq80x68/giphy.gif](https://media.giphy.com/media/MSS0COPq80x68/giphy.gif)