CallToActionItem missing fields
paked/messenger pull request #22
Opened 2016-12-08 13:49 UTC by Depado

Hey there 🎉 

Just noticed there were two missing fields in the `CallToActionItem` struct. 

See [this page](https://developers.facebook.com/docs/messenger-platform/thread-settings/persistent-menu) and especially the `menu_item` section for more details. 

`WebviewHeightRatio` was tested and works. Possible values (as described in the messenger docs) are : `compact`, `tall` or `full`

Thanks again for your great work, and I hope that will help ! 🎆

2016-12-08 20:56 UTC, paked requested changes

2016-12-08 20:56 UTC, paked commented on settings.go
> +	WebviewHeightRatio string `json:"webview_height_ratio,omitempty"`
You mention in your comment about there being only three different values which are currently valid here. Personally, I think this warrants use of a constant.

I'd go for something like:

```go
const (
  WebviewCompact = iota
  WebviewFull
  WebviewTall
)
```

2016-12-08 20:57 UTC, paked commented
Once we have this one change, I'll be more than happy to merge it in. 😀

2016-12-09 09:20 UTC, Depado commented on settings.go
> +	WebviewHeightRatio string `json:"webview_height_ratio,omitempty"`
Sure thing ! 🎈

2016-12-09 09:55 UTC, Depado commented
Hope that suits what you wanted, I quite didn't see how to use the `iota` mechanism in that case though.

2016-12-09 10:00 UTC, paked commented
@Depado Yours was a much better way :) I must have been half asleep when I was thinking about the `iota` stuff!

2016-12-09 10:00 UTC, paked approved these changes

2016-12-09 10:04 UTC, Depado commented
Thanks a lot for reviewing my changes and helping me improve 🎉

2016-12-09 10:04 UTC, merged

2016-12-09 10:04 UTC, paked commented
Thanks for the PR! (and working around my slightly-sleep-induced-crazy-review-requests)

![http://reactiongif.org/wp-content/uploads/GIF/2014/08/Thank-you---Guardians-of-the-Galaxy--GIF.gif](http://reactiongif.org/wp-content/uploads/GIF/2014/08/Thank-you---Guardians-of-the-Galaxy--GIF.gif)