Add AttachmentWithReplies method for sending attachment together with replies.
paked/messenger pull request #27
Opened 2017-03-08 21:35 UTC by opiuman

Be able to send attachment with replies in one reply

2017-03-14 17:56 UTC, paked requested changes
Sorry it's taken me so long to get back to you on this!

Thanks for the PR, I've made a few comments about stylistic changes. After that, everything should be good.

2017-03-14 17:56 UTC, paked commented on messenger.go
> +//SendGeneralMessage will send the GenericTemplate message
Would you mind putting a space here, between the `//` and `Send...`, want to make sure that we're following good [GoDoc comment styling](https://blog.golang.org/godoc-documenting-go-code).

2017-03-14 17:56 UTC, paked commented on response.go
> +// MessageData is a text Or attachment message with optional replies to be sent.
I'd change this to:

> // MessageData is a message consisting of text or an attachment, with an additional selection of optional quick replies.

2017-03-15 01:28 UTC, opiuman commented on messenger.go
> +//SendGeneralMessage will send the GenericTemplate message
Done.

2017-03-15 01:28 UTC, opiuman commented on response.go
> +// MessageData is a text Or attachment message with optional replies to be sent.
make sense. done

2017-03-15 17:28 UTC, opiuman commented
The change has made.

2017-03-15 17:29 UTC, merged

2017-03-15 17:32 UTC, paked commented
![https://media.giphy.com/media/l3q2UdX8HREZi35gA/source.gif](https://media.giphy.com/media/l3q2UdX8HREZi35gA/source.gif)