Adds integrity check (#19)
paked/messenger pull request #30
Opened 2017-06-20 00:03 UTC by RaMin0

2017-06-21 07:23 UTC, paked commented
@RaMin0: Thanks for submitting this PR :)

I'm pretty busy right now, but hopefully I can get around to it in the next 48 hours.

If I don't, feel free to pester me.

2017-06-26 09:45 UTC, RaMin0 commented
@paked Dong Dong Dong 🛎

2017-06-26 17:07 UTC, paked requested changes
Thanks for submitting this PR! I've been meaning to write this code for quite a while now.

One change, and then we're good to go. Thank you :heart:

2017-06-26 17:07 UTC, paked commented on cmd/bot/main.go
> +	port = flag.Int("p", 8080, "The port used to serve the messenger bot")
I'd prefer to only use one configuration package.

Could you rewrite this as:

`port = Flag.Int("port", 8080, "The port used to serve the messenger bot")`

You can provide the parameter as `./messenger-bot --port=4040` in the same way you would a normal `flag`.

Remember to remove all references to the `flag` package.

2017-06-28 00:52 UTC, RaMin0 commented on cmd/bot/main.go
> +	port = flag.Int("p", 8080, "The port used to serve the messenger bot")
@paked Fixed in c3bdb1b.

2017-06-28 02:10 UTC, merged

2017-06-28 02:11 UTC, paked commented
![https://media.giphy.com/media/Dnt2VnWFknFNm/giphy.gif](https://media.giphy.com/media/Dnt2VnWFknFNm/giphy.gif)

Thank you!